import type { ComponentProps } from "react";
import {
  IconArchive,
  IconArrowDown,
  IconArrowUp,
  IconBinary,
  IconBold,
  IconBrandAngular,
  IconBrandCSharp,
  IconBrandCpp,
  IconBrandDocker,
  IconBrandFlutter,
  IconBrandGit,
  IconBrandGolang,
  IconBrandGraphql,
  IconBrandJavascript,
  IconBrandKotlin,
  IconBrandNodejs,
  IconBrandNpm,
  IconBrandPowershell,
  IconBrandPython,
  IconBrandSass,
  IconBrandSvelte,
  IconBrandSwift,
  IconBrandTerraform,
  IconBrandTypescript,
  IconBraces,
  IconChevronRight,
  IconCircleCheck,
  IconCoffee,
  IconDatabase,
  IconFile,
  IconFileCode,
  IconFileMusic,
  IconFilePlus,
  IconFileText,
  IconFileTypeBmp,
  IconFileTypeCss,
  IconFileTypeCsv,
  IconFileTypeDoc,
  IconFileTypeDocx,
  IconFileTypeHtml,
  IconFileTypeJpg,
  IconFileTypeJs,
  IconFileTypeJsx,
  IconFileTypePdf,
  IconFileTypePhp,
  IconFileTypePng,
  IconFileTypePpt,
  IconFileTypeRs,
  IconFileTypeSql,
  IconFileTypeSvg,
  IconFileTypeTs,
  IconFileTypeTsx,
  IconFileTypeTxt,
  IconFileTypeVue,
  IconFileTypeXls,
  IconFileTypeXml,
  IconFileZip,
  IconFolder,
  IconFolderPlus,
  IconItalic,
  IconJson,
  IconLink,
  IconLock,
  IconLockOpen,
  IconMarkdown,
  IconPhoto,
  IconRefresh,
  IconSettings,
  IconStrikethrough,
  IconTerminal2,
  IconTypography,
  IconVideo,
  IconX,
} from "@tabler/icons-react";

type IconProps = ComponentProps<typeof IconFile>;
type IconComponent = typeof IconFile;

export const FileIcon = IconFile;
export const FolderIcon = IconFolder;
export const GearIcon = IconSettings;
export const ImageIcon = IconPhoto;
export const VideoIcon = IconVideo;
export const MarkdownIcon = IconMarkdown;
export const FolderPlusIcon = IconFolderPlus;
export const FilePlusIcon = IconFilePlus;
export const CloseIcon = IconX;
export const BoldIcon = IconBold;
export const ItalicIcon = IconItalic;
export const StrikeIcon = IconStrikethrough;
export const LinkIcon = IconLink;
export const ArrowUpIcon = IconArrowUp;
export const ArrowDownIcon = IconArrowDown;
export const RefreshIcon = IconRefresh;
export const CheckCircleIcon = IconCircleCheck;

export function ChevronIcon({ open, className = "", ...props }: IconProps & { open?: boolean }) {
  return (
    <IconChevronRight
      {...props}
      className={`transition-transform ${open ? "rotate-90" : ""} ${className}`}
    />
  );
}

export function LockIcon({ open, ...props }: IconProps & { open?: boolean }) {
  const Icon = open ? IconLockOpen : IconLock;
  return <Icon {...props} />;
}

const extensionIcons: Record<string, IconComponent> = {
  md: IconMarkdown,
  markdown: IconMarkdown,
  mdown: IconMarkdown,
  mdx: IconMarkdown,
  py: IconBrandPython,
  pyw: IconBrandPython,
  js: IconFileTypeJs,
  mjs: IconBrandJavascript,
  cjs: IconBrandNodejs,
  jsx: IconFileTypeJsx,
  ts: IconFileTypeTs,
  mts: IconBrandTypescript,
  cts: IconBrandTypescript,
  tsx: IconFileTypeTsx,
  html: IconFileTypeHtml,
  htm: IconFileTypeHtml,
  css: IconFileTypeCss,
  scss: IconBrandSass,
  sass: IconBrandSass,
  less: IconFileTypeCss,
  vue: IconFileTypeVue,
  svelte: IconBrandSvelte,
  go: IconBrandGolang,
  rs: IconFileTypeRs,
  java: IconCoffee,
  kt: IconBrandKotlin,
  kts: IconBrandKotlin,
  swift: IconBrandSwift,
  dart: IconBrandFlutter,
  php: IconFileTypePhp,
  cs: IconBrandCSharp,
  c: IconBrandCpp,
  h: IconBrandCpp,
  cc: IconBrandCpp,
  cpp: IconBrandCpp,
  cxx: IconBrandCpp,
  hpp: IconBrandCpp,
  rb: IconFileCode,
  lua: IconFileCode,
  r: IconFileCode,
  m: IconFileCode,
  mm: IconFileCode,
  vb: IconFileCode,
  pl: IconFileCode,
  pm: IconFileCode,
  fs: IconFileCode,
  fsx: IconFileCode,
  groovy: IconFileCode,
  cr: IconFileCode,
  nim: IconFileCode,
  zig: IconFileCode,
  sol: IconFileCode,
  coffee: IconCoffee,
  scala: IconFileCode,
  clj: IconFileCode,
  ex: IconFileCode,
  exs: IconFileCode,
  erl: IconFileCode,
  hs: IconFileCode,
  asm: IconFileCode,
  s: IconFileCode,
  json: IconJson,
  jsonc: IconJson,
  json5: IconJson,
  yaml: IconBraces,
  yml: IconBraces,
  toml: IconBraces,
  xml: IconFileTypeXml,
  plist: IconFileTypeXml,
  sql: IconFileTypeSql,
  sqlite: IconDatabase,
  sqlite3: IconDatabase,
  db: IconDatabase,
  graphql: IconBrandGraphql,
  gql: IconBrandGraphql,
  proto: IconFileCode,
  cmake: IconFileCode,
  ipynb: IconJson,
  sh: IconTerminal2,
  bash: IconTerminal2,
  zsh: IconTerminal2,
  fish: IconTerminal2,
  ps1: IconBrandPowershell,
  bat: IconTerminal2,
  cmd: IconTerminal2,
  dockerfile: IconBrandDocker,
  tf: IconBrandTerraform,
  tfvars: IconBrandTerraform,
  gradle: IconCoffee,
  properties: IconFileText,
  ini: IconFileText,
  conf: IconFileText,
  cfg: IconFileText,
  env: IconFileText,
  editorconfig: IconFileText,
  diff: IconFileText,
  patch: IconFileText,
  lock: IconFileText,
  mod: IconFileText,
  sum: IconFileText,
  log: IconFileTypeTxt,
  txt: IconFileTypeTxt,
  text: IconFileTypeTxt,
  csv: IconFileTypeCsv,
  pdf: IconFileTypePdf,
  doc: IconFileTypeDoc,
  docx: IconFileTypeDocx,
  rtf: IconFileTypeDoc,
  xls: IconFileTypeXls,
  xlsx: IconFileTypeXls,
  ods: IconFileTypeXls,
  ppt: IconFileTypePpt,
  pptx: IconFileTypePpt,
  odp: IconFileTypePpt,
  png: IconFileTypePng,
  jpg: IconFileTypeJpg,
  jpeg: IconFileTypeJpg,
  bmp: IconFileTypeBmp,
  svg: IconFileTypeSvg,
  gif: IconPhoto,
  webp: IconPhoto,
  ico: IconPhoto,
  avif: IconPhoto,
  tif: IconPhoto,
  tiff: IconPhoto,
  mp4: IconVideo,
  webm: IconVideo,
  mov: IconVideo,
  m4v: IconVideo,
  mkv: IconVideo,
  avi: IconVideo,
  ogv: IconVideo,
  mp3: IconFileMusic,
  wav: IconFileMusic,
  flac: IconFileMusic,
  aac: IconFileMusic,
  m4a: IconFileMusic,
  ogg: IconFileMusic,
  zip: IconFileZip,
  tar: IconArchive,
  gz: IconArchive,
  bz2: IconArchive,
  xz: IconArchive,
  "7z": IconArchive,
  rar: IconArchive,
  tgz: IconArchive,
  apk: IconArchive,
  dmg: IconArchive,
  jar: IconArchive,
  woff: IconTypography,
  woff2: IconTypography,
  ttf: IconTypography,
  otf: IconTypography,
  exe: IconBinary,
  dll: IconBinary,
  bin: IconBinary,
  wasm: IconBinary,
};

const basenameIcons: Record<string, IconComponent> = {
  dockerfile: IconBrandDocker,
  "docker-compose.yml": IconBrandDocker,
  "docker-compose.yaml": IconBrandDocker,
  "compose.yml": IconBrandDocker,
  "compose.yaml": IconBrandDocker,
  "package.json": IconBrandNpm,
  "package-lock.json": IconBrandNpm,
  "npm-shrinkwrap.json": IconBrandNpm,
  "angular.json": IconBrandAngular,
  ".gitignore": IconBrandGit,
  ".gitattributes": IconBrandGit,
  ".gitmodules": IconBrandGit,
  ".dockerignore": IconBrandDocker,
  ".editorconfig": IconFileText,
  makefile: IconTerminal2,
  gemfile: IconFileCode,
  rakefile: IconFileCode,
  license: IconFileText,
  copying: IconFileText,
};

export function FileTypeIcon({
  name,
  kind: _kind,
  isDir = false,
  ...props
}: IconProps & { name: string; kind?: string; isDir?: boolean }) {
  if (isDir) {
    return <IconFolder {...props} />;
  }
  const base = name.split(/[/\\]/).pop()?.toLowerCase() ?? name.toLowerCase();
  const extension = base.includes(".") ? base.split(".").pop() ?? "" : "";
  // File name is the single source of truth so a tab and its tree row always
  // resolve to exactly the same icon. Extensionless documents follow Veda's
  // existing classification and are treated as Markdown.
  const fallback = extension ? IconFile : IconMarkdown;
  const Icon = basenameIcons[base] ?? extensionIcons[extension] ?? fallback;
  return <Icon {...props} />;
}
