// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 是暴露给前端的 API。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate 主动检查一次更新。检查与下载在后台进行，
 * 前端通过 GetUpdateState 轮询进度。
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateState | null> {
    return $Call.ByID(2651044200);
}

/**
 * CloseWindow 关闭当前窗口。前端在没有标签页可关的时候调用它。
 */
export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(4083233194);
}

/**
 * CopyFile 把文件或文件夹放进系统剪贴板，以便在文件管理器里粘贴。
 */
export function CopyFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1105439977, path);
}

/**
 * CreateFolder 在 parent 下创建一个不重名的文件夹。
 */
export function CreateFolder(parent: string, name: string): $CancellablePromise<$models.FileEntry | null> {
    return $Call.ByID(3863529870, parent, name);
}

/**
 * CreateMarkdown 在 parent 下创建一个不重名的 Markdown 文件。
 */
export function CreateMarkdown(parent: string, name: string): $CancellablePromise<$models.FileEntry | null> {
    return $Call.ByID(2462821979, parent, name);
}

/**
 * Delete 永久删除文件或文件夹，当前工作区根目录不允许删除。
 */
export function Delete(path: string): $CancellablePromise<void> {
    return $Call.ByID(2416349173, path);
}

/**
 * GetAppInfo 返回「关于」页面需要的版本与平台信息。
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo | null> {
    return $Call.ByID(4184398461);
}

/**
 * GetFileLock 返回文档已持久化的锁定状态，没有记录时默认为编辑模式。
 */
export function GetFileLock(workspacePath: string, filePath: string): $CancellablePromise<$models.FileLockState | null> {
    return $Call.ByID(2172180487, workspacePath, filePath);
}

/**
 * GetLayout 加载工作区的界面布局（侧边栏宽度与窗口几何信息）。
 */
export function GetLayout(workspacePath: string): $CancellablePromise<$models.WorkspaceLayout | null> {
    return $Call.ByID(1732508512, workspacePath);
}

/**
 * GetSession 返回最近一次保存的工作区。
 */
export function GetSession(): $CancellablePromise<$models.Session | null> {
    return $Call.ByID(4287414074);
}

/**
 * GetSettings 加载全局设置，以及可选的工作区设置。
 */
export function GetSettings(workspacePath: string): $CancellablePromise<$models.SettingsBundle | null> {
    return $Call.ByID(3018893939, workspacePath);
}

/**
 * GetUpdateState 返回更新检查与下载的当前状态。
 */
export function GetUpdateState(): $CancellablePromise<$models.UpdateState | null> {
    return $Call.ByID(3686901152);
}

/**
 * ImportImageData 保存以 base64 编码传入的本地图片或粘贴图片。
 */
export function ImportImageData(workspacePath: string, name: string, contentType: string, encoded: string): $CancellablePromise<$models.ImportedAsset | null> {
    return $Call.ByID(4168017972, workspacePath, name, contentType, encoded);
}

/**
 * InstallUpdate 安装已下载的更新并重启应用。
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3729456840);
}

/**
 * MediaURL 返回本地媒体文件对应的资源服务器 URL。
 */
export function MediaURL(path: string): $CancellablePromise<string> {
    return $Call.ByID(865123779, path);
}

/**
 * MoveToTrash 把文件或文件夹交给系统回收站处理。
 */
export function MoveToTrash(path: string): $CancellablePromise<void> {
    return $Call.ByID(1780663512, path);
}

/**
 * NewWindow 再打开一个应用窗口。
 */
export function NewWindow(): $CancellablePromise<void> {
    return $Call.ByID(168487400);
}

/**
 * OpenURL 用系统默认浏览器打开链接。
 */
export function OpenURL(raw: string): $CancellablePromise<void> {
    return $Call.ByID(790318107, raw);
}

/**
 * PickDirectory 打开系统原生的文件夹选择对话框。
 */
export function PickDirectory(): $CancellablePromise<$models.OpenTarget | null> {
    return $Call.ByID(4292351642);
}

/**
 * PickFile 打开系统原生的文件选择对话框。
 */
export function PickFile(): $CancellablePromise<$models.OpenTarget | null> {
    return $Call.ByID(870419925);
}

/**
 * ReadDir 列出目录内容。
 */
export function ReadDir(path: string): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(870691193, path);
}

/**
 * ReadText 读取 Markdown 或纯文本文件。
 */
export function ReadText(path: string): $CancellablePromise<$models.TextFile | null> {
    return $Call.ByID(3489741593, path);
}

/**
 * Rename 原地重命名文件或文件夹。
 */
export function Rename(path: string, newName: string): $CancellablePromise<$models.FileEntry | null> {
    return $Call.ByID(2637606580, path, newName);
}

/**
 * ResolveImagePath 解析工作区内的资源链接，并在单文件模式下按回退规则查找。
 */
export function ResolveImagePath(workspacePath: string, fromDir: string, src: string): $CancellablePromise<string> {
    return $Call.ByID(2591528072, workspacePath, fromDir, src);
}

/**
 * ResolvePath 把目录和一个（可能是相对的）路径拼接起来。
 */
export function ResolvePath(fromDir: string, src: string): $CancellablePromise<string> {
    return $Call.ByID(3758697577, fromDir, src);
}

/**
 * RevealInFileManager 在 Finder、资源管理器或系统文件管理器中定位文件或文件夹。
 */
export function RevealInFileManager(path: string): $CancellablePromise<void> {
    return $Call.ByID(180266905, path);
}

/**
 * SaveFileLock 记录文档当前处于编辑模式还是只读模式。
 */
export function SaveFileLock(workspacePath: string, filePath: string, editing: boolean): $CancellablePromise<void> {
    return $Call.ByID(3362615718, workspacePath, filePath, editing);
}

/**
 * SaveHeadingPanelWidth 记录该工作区的 Markdown 大纲面板宽度。
 */
export function SaveHeadingPanelWidth(workspacePath: string, width: number): $CancellablePromise<$models.WorkspaceLayout | null> {
    return $Call.ByID(3419312925, workspacePath, width);
}

/**
 * SaveOpenTabs 记录该工作区已打开的标签页路径（不含文件内容）。
 */
export function SaveOpenTabs(workspacePath: string, tabs: string[] | null, active: string): $CancellablePromise<$models.WorkspaceLayout | null> {
    return $Call.ByID(1239682819, workspacePath, tabs, active);
}

/**
 * SaveSession 写入当前选定的工作区，并把它绑定到发起调用的窗口上，
 * 这样窗口关闭时能把同一个工作区写回 session.json。
 */
export function SaveSession(kind: string, path: string, file: string): $CancellablePromise<void> {
    return $Call.ByID(1833592449, kind, path, file);
}

/**
 * SaveSettings 以 JSON 形式写入一份设置文档。
 */
export function SaveSettings(scope: string, workspacePath: string, settingsJSON: string): $CancellablePromise<$models.SettingsBundle | null> {
    return $Call.ByID(3784651466, scope, workspacePath, settingsJSON);
}

/**
 * SaveSidebarWidth 记录该工作区的目录树宽度。
 */
export function SaveSidebarWidth(workspacePath: string, width: number): $CancellablePromise<$models.WorkspaceLayout | null> {
    return $Call.ByID(1163423635, workspacePath, width);
}

/**
 * SearchContent 在内存中的文本（含未保存的草稿）里匹配查询词。
 */
export function SearchContent(content: string, query: string, opts: $models.SearchOptions): $CancellablePromise<$models.SearchResult | null> {
    return $Call.ByID(410169307, content, query, opts);
}

/**
 * SearchWorkspace 遍历文件夹，匹配 Markdown 及其他文本文件。
 */
export function SearchWorkspace(workspacePath: string, query: string, opts: $models.SearchOptions): $CancellablePromise<$models.SearchResult | null> {
    return $Call.ByID(2068548899, workspacePath, query, opts);
}

/**
 * Stat 返回某个路径的元信息。
 */
export function Stat(path: string): $CancellablePromise<$models.FileMeta | null> {
    return $Call.ByID(1965543488, path);
}

/**
 * WriteText 保存文本文件，不会改动操作系统层面的文件权限。
 */
export function WriteText(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(254991214, path, content);
}
