// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings 是持久化后的设置文档。
 */
export interface AppSettings {
    "general": GeneralSettings;
    "markdown": MarkdownSettings;
    "shortcuts": ShortcutSettings;
}

/**
 * FileEntry 是目录列表中的一行。
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "kind": string;
}

/**
 * FileLockState 是文档持久化的锁定状态（只读还是可编辑）。
 */
export interface FileLockState {
    "found": boolean;
    "editing": boolean;
}

/**
 * FileMeta 描述磁盘上的一个路径。
 */
export interface FileMeta {
    "name": string;
    "path": string;
    "dir": string;
    "isDir": boolean;
    "kind": string;
    "writable": boolean;
    "size": number;
    "exists": boolean;
}

/**
 * FileSearchResult 把同一个路径下的命中结果聚合在一起。
 */
export interface FileSearchResult {
    "path": string;
    "relPath"?: string;
    "kind": string;
    "matches": SearchMatch[] | null;
}

/**
 * GeneralSettings 是应用级别的界面偏好设置。
 */
export interface GeneralSettings {
    "theme": string;
    "language": string;

    /**
     * Startup 仅对全局设置生效："last" 恢复上次的工作区，"launch" 打开启动页。
     */
    "startup": string;

    /**
     * AutoReadonly 为 true 时文档以锁定状态打开；为 false 时每个文件的锁定状态单独持久化。
     */
    "autoReadonly": boolean;

    /**
     * ResourceDirectory 相对于工作区根目录；单文件窗口下则相对于 ~/.veda。
     */
    "resourceDirectory": string;

    /**
     * ShowResourceDirectory 控制工作区目录树是否显示资源目录。
     */
    "showResourceDirectory": boolean;

    /**
     * MaxDocTabs 是每个窗口最多保留的文档标签页数量。
     */
    "maxDocTabs": number;

    /**
     * DocTabsLayout 控制标签页单行滚动或多行换行显示。
     */
    "docTabsLayout": string;
}

/**
 * ImportedAsset 描述已保存的图片，以及要插入到 Markdown 里的路径。
 */
export interface ImportedAsset {
    "name": string;
    "path": string;
    "markdownPath": string;
}

/**
 * MarkdownSettings 控制编辑区画布以及 Markdown 的渲染效果。
 */
export interface MarkdownSettings {
    "editorWidth": string;
    "showHeadingPanel": boolean;
    "styles": MarkdownStyles;
}

/**
 * MarkdownStyle 是单个 Markdown 元素的渲染样式，可由用户修改。
 */
export interface MarkdownStyle {
    "color": ThemeColor;
    "background": ThemeColor;
    "fontSize": string;
    "fontFamily": string;
    "bold": boolean;
    "italic": boolean;
}

/**
 * MarkdownStyles 列出编辑器能渲染的全部 Markdown 元素。
 */
export interface MarkdownStyles {
    "paragraph": MarkdownStyle;
    "heading1": MarkdownStyle;
    "heading2": MarkdownStyle;
    "heading3": MarkdownStyle;
    "heading4": MarkdownStyle;
    "heading5": MarkdownStyle;
    "heading6": MarkdownStyle;
    "strong": MarkdownStyle;
    "emphasis": MarkdownStyle;
    "strikethrough": MarkdownStyle;
    "link": MarkdownStyle;
    "inlineCode": MarkdownStyle;
    "codeBlock": MarkdownStyle;
    "blockquote": MarkdownStyle;
    "unorderedList": MarkdownStyle;
    "orderedList": MarkdownStyle;
    "listItem": MarkdownStyle;
    "taskList": MarkdownStyle;
    "taskChecked": MarkdownStyle;
    "table": MarkdownStyle;
    "tableHeader": MarkdownStyle;
    "tableCell": MarkdownStyle;
    "hr": MarkdownStyle;
    "image": MarkdownStyle;
}

/**
 * OpenTarget 是用户打开的文件或目录。
 */
export interface OpenTarget {
    /**
     * "file" | "directory"
     */
    "kind": string;
    "path": string;
    "file"?: string;
}

/**
 * SearchMatch 表示文件中的一处命中。
 */
export interface SearchMatch {
    "line": number;
    "column": number;
    "endLine": number;
    "endColumn": number;
    "startByte": number;
    "endByte": number;
    "match": string;
    "lineText": string;
    "before"?: string[] | null;
    "after"?: string[] | null;
}

/**
 * SearchOptions 决定查询词的匹配方式。
 */
export interface SearchOptions {
    "caseSensitive": boolean;
    "wholeWord": boolean;
    "useRegex": boolean;
    "maxMatches": number;
    "maxPerFile": number;
    "contextLines": number;
}

/**
 * SearchResult 是返回给编辑器的数据结构。
 */
export interface SearchResult {
    "query": string;
    "scannedFiles": number;
    "skippedFiles"?: number;
    "truncated": boolean;
    "files": FileSearchResult[] | null;
}

/**
 * Session 持久化在 ~/.veda/session.json 中。
 */
export interface Session {
    "last"?: OpenTarget | null;
}

/**
 * SettingsBundle 是设置界面一次请求就能加载到的全部内容。
 */
export interface SettingsBundle {
    "global": AppSettings;
    "workspace": AppSettings;
    "workspaceExists": boolean;
}

/**
 * ShortcutSettings 保存可配置的命令快捷键。
 * 空字符串表示该命令未绑定快捷键；JSON 中缺失的字段则沿用默认值。
 */
export interface ShortcutSettings {
    "searchCurrentFile": string;
    "searchWorkspace": string;
    "closeTab": string;
}

/**
 * TextFile 是可编辑/可查看文本的数据结构。
 */
export interface TextFile {
    "name": string;
    "path": string;
    "dir": string;
    "isDir": boolean;
    "kind": string;
    "writable": boolean;
    "size": number;
    "exists": boolean;
    "content": string;
}

/**
 * ThemeColor 是 Markdown 样式使用的浅色/深色配色对。
 */
export interface ThemeColor {
    "light": string;
    "dark": string;
}

/**
 * WindowLayout 是某个工作区最后一次记录的窗口几何信息。
 */
export interface WindowLayout {
    "screenID"?: string;
    "screenName"?: string;
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximized"?: boolean;
    "fullscreen"?: boolean;
}

/**
 * WorkspaceLayout 持久化在 ~/.veda/{workspace-uuid}/layout.json 中。
 */
export interface WorkspaceLayout {
    "sidebarWidth"?: number;
    "headingPanelWidth"?: number;
    "openTabs"?: string[] | null;
    "activeTab"?: string;
    "window"?: WindowLayout | null;
}
